# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlistitem',
            name='bucketlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucketlistitem', to='api.BucketList'),
        ),
        migrations.AlterUniqueTogether(
            name='bucketlistitem',
            unique_together=set([('bucketlist', 'item_name')]),
        ),
    ]
