# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-07 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160711_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlistitem',
            name='item_description',
        ),
    ]
